set(_CATKIN_CURRENT_PACKAGE "mecanum_robot_slam")
set(mecanum_robot_slam_VERSION "0.0.0")
set(mecanum_robot_slam_MAINTAINER "drcl-yang <drcl-yang@todo.todo>")
set(mecanum_robot_slam_PACKAGE_FORMAT "2")
set(mecanum_robot_slam_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(mecanum_robot_slam_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(mecanum_robot_slam_BUILDTOOL_DEPENDS "catkin")
set(mecanum_robot_slam_BUILDTOOL_EXPORT_DEPENDS )
set(mecanum_robot_slam_EXEC_DEPENDS "roscpp" "sensor_msgs")
set(mecanum_robot_slam_RUN_DEPENDS "roscpp" "sensor_msgs")
set(mecanum_robot_slam_TEST_DEPENDS )
set(mecanum_robot_slam_DOC_DEPENDS )
set(mecanum_robot_slam_URL_WEBSITE "")
set(mecanum_robot_slam_URL_BUGTRACKER "")
set(mecanum_robot_slam_URL_REPOSITORY "")
set(mecanum_robot_slam_DEPRECATED "")